# Generated by Django 5.2.1 on 2025-08-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_variantsoptions_productimage_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_selling_price', models.FloatField()),
                ('dealer_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_fee', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopkeeper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
