# Generated by Django 5.2.1 on 2025-08-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantsoptions',
            old_name='variant_option',
            new_name='option_name',
        ),
    ]
